export { default as Catalog } from './catalog/Catalog'
export { default as Footer } from './catalog/Catalog'
export { default as Hero } from './hero/Hero'
export { default as Mobile } from './mobile/Mobile'
export { default as Testimonial } from './testimonial/Testimonial'