export const data = [
    {
        id: 1,
        name: "Any Day Offers",
        desc: "Krispy Burger",
        price: "Rp. 20.999",
        img: "../../assets/catalog01.png",
    },
    {
        id: 2,
        name: "Ala Karte Special",
        desc: "Colonel Yakiniku",
        price: "Rp. 35.999",
        img: "../../assets/catalog02.png",
    },
    {
        id: 3,
        name: "Zuper Box",
        desc: "Nasi + Ayam + Zuper Krunch + Minuman",
        price: "Rp. 55.999",
        img: "../../assets/catalog03.png",
    },
    {
        id: 4,
        name: "Special Combo Duos",
        desc: "Nasi + Ayam + French Fries + Krispy Burger + Winger + Minuman",
        price: "Rp. 50.999",
        img: "../../assets/catalog04.png",
    },
    {
        id: 5,
        name: "Special Combo Family",
        desc: "Nasi + Ayam + French Fries + Winger + Minuman",
        price: "Rp. 190.999",
        img: "../../assets/catalog05.png",
    },
    {
        id: 6,
        name: "Super Family HCC",
        desc: "",
        price: "Rp. 45.999",
        img: "../../assets/carousel01.png",
    },
    {
        id: 7,
        name: "9Pcs Wings Bucket",
        desc: "",
        price: "Rp. 35.999",
        img: "../../assets/carousel02.png",
    },
    {
        id: 8,
        name: "Wings Bucket",
        desc: "",
        price: "Rp. 25.999",
        img: "../../assets/carousel03.png",
    },
    {
        id: 9,
        name: "Winger Combo BBQ",
        desc: "",
        price: "Rp. 22.999",
        img: "../../assets/carousel04.png",
    },
    {
        id: 10,
        name: "Snack Bucket 1",
        desc: "",
        price: "Rp. 25.999",
        img: "../../assets/carousel05.png",
    },
];
